/*
Proyecto Final: Pronostico de Personal
CIA: Kenworth Mexicana
Asignatura: Desarrollo de Software
Catedratico: Maria Angelica Astorga
Equipo: Adrian Heredia, Sergio Salomon, Edgar Pescador, Hector Montes, Jaime Rodriguez
Fecha: Junio 2018.
*/
package kenworthpronostico;

import javax.swing.JOptionPane;
import kwnegocio.procesos;

public class jDagregarModel extends javax.swing.JDialog {
    procesos pr = new procesos();
    
    public jDagregarModel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jT2ejestiempo.setEnabled(false);
        jT3ejestiempo.setEnabled(false);
        lbmensaje.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPAgregarModel = new javax.swing.JPanel();
        jPanelAgModel = new javax.swing.JPanel();
        jLmodel = new javax.swing.JLabel();
        jTagModel = new javax.swing.JTextField();
        jLMot = new javax.swing.JLabel();
        jTagMotor = new javax.swing.JTextField();
        jLtiempoMot = new javax.swing.JLabel();
        jC2ejestiempo = new javax.swing.JCheckBox();
        jC3ejestiempo = new javax.swing.JCheckBox();
        jLeje = new javax.swing.JLabel();
        jTtiempoMot = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jT2ejestiempo = new javax.swing.JTextField();
        jT3ejestiempo = new javax.swing.JTextField();
        lbmensaje = new javax.swing.JLabel();
        jbAddModel = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLtitulModel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPAgregarModel.setBackground(new java.awt.Color(255, 255, 255));

        jPanelAgModel.setBackground(new java.awt.Color(255, 255, 255));

        jLmodel.setText("Ingresar Modelo");

        jLMot.setText("Ingresar Motor");

        jLtiempoMot.setText("Ingresar Tiempo de Motor");

        jC2ejestiempo.setText("2 Ejes");
        jC2ejestiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC2ejestiempoActionPerformed(evt);
            }
        });

        jC3ejestiempo.setText("3 Ejes");
        jC3ejestiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC3ejestiempoActionPerformed(evt);
            }
        });

        jLeje.setText("Ingresar Ejes");

        jTtiempoMot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTtiempoMotKeyTyped(evt);
            }
        });

        jLabel1.setText("Ingresar Tiempo de Ejes");

        jT2ejestiempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jT2ejestiempoKeyTyped(evt);
            }
        });

        jT3ejestiempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jT3ejestiempoKeyTyped(evt);
            }
        });

        lbmensaje.setText("jLabel2");
        lbmensaje.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jbAddModel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAddModel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check.png"))); // NOI18N
        jbAddModel.setText("Agregar");
        jbAddModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddModelActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancelar2.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgModelLayout = new javax.swing.GroupLayout(jPanelAgModel);
        jPanelAgModel.setLayout(jPanelAgModelLayout);
        jPanelAgModelLayout.setHorizontalGroup(
            jPanelAgModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgModelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelAgModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgModelLayout.createSequentialGroup()
                        .addComponent(jLmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelAgModelLayout.createSequentialGroup()
                        .addGroup(jPanelAgModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelAgModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelAgModelLayout.createSequentialGroup()
                                    .addComponent(jLeje)
                                    .addGap(130, 130, 130)
                                    .addComponent(jC2ejestiempo)
                                    .addGap(0, 0, 0)
                                    .addComponent(jC3ejestiempo))
                                .addGroup(jPanelAgModelLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(78, 78, 78)
                                    .addComponent(jT2ejestiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(jT3ejestiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelAgModelLayout.createSequentialGroup()
                                    .addGroup(jPanelAgModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLMot)
                                        .addComponent(jLtiempoMot))
                                    .addGap(39, 39, 39)
                                    .addGroup(jPanelAgModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTtiempoMot, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTagMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTagModel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAgModelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jbAddModel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 28, Short.MAX_VALUE))))
        );
        jPanelAgModelLayout.setVerticalGroup(
            jPanelAgModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgModelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelAgModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLmodel)
                    .addComponent(jTagModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAgModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMot)
                    .addComponent(jTagMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAgModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtiempoMot)
                    .addComponent(jTtiempoMot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAgModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgModelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLeje))
                    .addComponent(jC2ejestiempo)
                    .addComponent(jC3ejestiempo))
                .addGap(18, 18, 18)
                .addGroup(jPanelAgModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgModelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(jT2ejestiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT3ejestiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lbmensaje)
                .addGap(18, 18, 18)
                .addGroup(jPanelAgModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAddModel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLtitulModel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLtitulModel.setText("Agregar Modelo");

        javax.swing.GroupLayout jPAgregarModelLayout = new javax.swing.GroupLayout(jPAgregarModel);
        jPAgregarModel.setLayout(jPAgregarModelLayout);
        jPAgregarModelLayout.setHorizontalGroup(
            jPAgregarModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAgregarModelLayout.createSequentialGroup()
                .addGroup(jPAgregarModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAgregarModelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLtitulModel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPAgregarModelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanelAgModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPAgregarModelLayout.setVerticalGroup(
            jPAgregarModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAgregarModelLayout.createSequentialGroup()
                .addComponent(jLtitulModel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanelAgModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPAgregarModel);
        jPAgregarModel.setBounds(0, 0, 420, 340);

        setBounds(0, 0, 434, 378);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jT2ejestiempoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT2ejestiempoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingresar solo numeros");
        }
    }//GEN-LAST:event_jT2ejestiempoKeyTyped

    private void jT3ejestiempoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT3ejestiempoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingresar solo numeros");
        }
    }//GEN-LAST:event_jT3ejestiempoKeyTyped

    private void jTtiempoMotKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtiempoMotKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingresar solo numeros");
        }
    }//GEN-LAST:event_jTtiempoMotKeyTyped

    private void jbAddModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddModelActionPerformed
        // TODO add your handling code here:
        int rvalue = allok();
        switch (rvalue){
            case 1: lbmensaje.setText("! Ingresar nombre del Modelo..."); break;
            case 2: lbmensaje.setText("! Ingresar tipo de Motor..."); break;
            case 3: lbmensaje.setText("! Ingresar tiempo de vestidura de Motor..."); break;
            case 4: lbmensaje.setText("! Seleccione la cantidad de Ejes..."); break;
            case 5: lbmensaje.setText("! Ingresar tiempo de vestidura de 2 Ejes..."); break;
            case 6: lbmensaje.setText("! Ingresar tiempo de vestidura de 3 Ejes..."); break;
            case 7: lbmensaje.setText("! El tiempo de vestidura no puede ser menor que 1..."); break;
            case 10: 
                lbmensaje.setText("! Procesando datos...");
                // funcion para agregar datos
                pr.addnewmodel(jTagModel.getText(), jTagMotor.getText(),
                                jTtiempoMot.getText(), jT2ejestiempo.getText(),
                                jT3ejestiempo.getText());
                lbmensaje.setText("! Datos agregados exitosamente..."); 
                break;
        }
       
    }//GEN-LAST:event_jbAddModelActionPerformed

    private void jC2ejestiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC2ejestiempoActionPerformed
        // TODO add your handling code here:
        if (jC2ejestiempo.isSelected()){
            jT2ejestiempo.setText("");
            jT2ejestiempo.setEnabled(true);
        }else{
            jT2ejestiempo.setEnabled(false);
        }
    }//GEN-LAST:event_jC2ejestiempoActionPerformed

    private void jC3ejestiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC3ejestiempoActionPerformed
        // TODO add your handling code here:
        if (jC3ejestiempo.isSelected()){
            jT3ejestiempo.setText("");
            jT3ejestiempo.setEnabled(true);
        }else{
            jT3ejestiempo.setEnabled(false);
        }        
    }//GEN-LAST:event_jC3ejestiempoActionPerformed
    // Verifica si todos los campos estan llenos
    private Integer allok(){
        if (jTagModel.getText().isEmpty()) return 1;
        if (jTagMotor.getText().isEmpty()) return 2;
        if (jTtiempoMot.getText().isEmpty()) return 3;
        if (!jC2ejestiempo.isSelected() && !jC3ejestiempo.isSelected()){
            return 4;
        }else{
            if(jC2ejestiempo.isSelected()){
                if(jT2ejestiempo.getText().isEmpty()){
                    return 5;
                }else{
                    double value =  Double.parseDouble(jT2ejestiempo.getText());
                    if (value <1){
                        jT2ejestiempo.setText("");
                        return 7;
                    }
                }                
            }
            if(jC3ejestiempo.isSelected()){
                if(jT3ejestiempo.getText().isEmpty()){
                    return 6;
                }else{
                    double value =  Double.parseDouble(jT3ejestiempo.getText());
                    if (value <1){
                        jT3ejestiempo.setText("");
                        return 7;
                    }
                }         
            }
        }
        return 10;
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDagregarModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDagregarModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDagregarModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDagregarModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                jDagregarModel dialog = new jDagregarModel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jC2ejestiempo;
    private javax.swing.JCheckBox jC3ejestiempo;
    private javax.swing.JLabel jLMot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLeje;
    private javax.swing.JLabel jLmodel;
    private javax.swing.JLabel jLtiempoMot;
    private javax.swing.JLabel jLtitulModel;
    private javax.swing.JPanel jPAgregarModel;
    private javax.swing.JPanel jPanelAgModel;
    private javax.swing.JTextField jT2ejestiempo;
    private javax.swing.JTextField jT3ejestiempo;
    private javax.swing.JTextField jTagModel;
    private javax.swing.JTextField jTagMotor;
    private javax.swing.JTextField jTtiempoMot;
    private javax.swing.JButton jbAddModel;
    private javax.swing.JLabel lbmensaje;
    // End of variables declaration//GEN-END:variables
}
