/*
Proyecto Final: Pronostico de Personal
CIA: Kenworth Mexicana
Asignatura: Desarrollo de Software
Catedratico: Maria Angelica Astorga
Equipo: Adrian Heredia, Sergio Salomon, Edgar Pescador, Hector Montes, Jaime Rodriguez
Fecha: Junio 2018.
*/
package 
        kenworthpronostico;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JOptionPane;
import kwnegocio.procesos;
import kwpersistencia.KWPersistencia;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class KenworthPronostico extends javax.swing.JFrame {

    float horaMotor, horasEjes2, horaEjes3, horaEjes4;
    int cantidadMotor, totalMotor, recursoMotor;
    int cont = 0;
    int total = 0;
    boolean val = false;
    int veces = 1;
    int js2=0,js3=0,js4=0,js5=0,js6=0,js7=0,js8=0;    
    Double TotEjes, TotMot;

    static KWPersistencia db;
    static procesos pr = new procesos();
    jDvistaPrev vista = new jDvistaPrev(this, true);
    static ArrayList<String> modelos = new ArrayList();
    static ArrayList<Integer> CantEjes = new ArrayList();
    static String ModelId;
    static String modelengine;
    SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy");

    public KenworthPronostico() throws ClassNotFoundException, SQLException {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Images/Logo.jpg")).getImage());
           
        db = new KWPersistencia();
        jPanelImagen.setVisible(true);
        jPanelPronos.setVisible(false);
        jPlinea2.setVisible(false);
        jPlinea3.setVisible(false);
        jPlinea4.setVisible(false);
        jPlinea5.setVisible(false);
        jPlinea6.setVisible(false);
        jPlinea7.setVisible(false);
        jPlinea8.setVisible(false);
        Date defaultdate = new Date();
        jdPronostico.setDate(defaultdate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImagen = new javax.swing.JPanel();
        jLimagen = new javax.swing.JLabel();
        jPanelPronos = new javax.swing.JPanel();
        jLejes = new javax.swing.JLabel();
        jBvistaPre = new javax.swing.JButton();
        jLunidad = new javax.swing.JLabel();
        jPejecucionPron = new javax.swing.JPanel();
        jPlinea3 = new javax.swing.JPanel();
        jSpinCantModelo3 = new javax.swing.JSpinner();
        jCselectModelo3 = new javax.swing.JComboBox<>();
        jCselectedEjes3 = new javax.swing.JCheckBox();
        jCcantEjes3 = new javax.swing.JComboBox<>();
        jLSeleccioneMotor1 = new javax.swing.JLabel();
        jPlinea4 = new javax.swing.JPanel();
        jSpinCantModelo4 = new javax.swing.JSpinner();
        jCselectModelo4 = new javax.swing.JComboBox<>();
        jCselectEjes4 = new javax.swing.JCheckBox();
        jCcantEjes4 = new javax.swing.JComboBox<>();
        jLSeleccioneMotor2 = new javax.swing.JLabel();
        jPlinea5 = new javax.swing.JPanel();
        jSpincantModelo5 = new javax.swing.JSpinner();
        jCselectModelo5 = new javax.swing.JComboBox<>();
        jCselectEjes5 = new javax.swing.JCheckBox();
        jCcantEjes5 = new javax.swing.JComboBox<>();
        jLSeleccioneMotor3 = new javax.swing.JLabel();
        jPlinea6 = new javax.swing.JPanel();
        jSpincantModelo6 = new javax.swing.JSpinner();
        jCselectModelo6 = new javax.swing.JComboBox<>();
        jCselectEjes6 = new javax.swing.JCheckBox();
        jCcantEjes6 = new javax.swing.JComboBox<>();
        jLSeleccioneMotor4 = new javax.swing.JLabel();
        jPlinea7 = new javax.swing.JPanel();
        jSpincantModelo7 = new javax.swing.JSpinner();
        jCselectModelo7 = new javax.swing.JComboBox<>();
        jCselectEjes7 = new javax.swing.JCheckBox();
        jCcantEjes7 = new javax.swing.JComboBox<>();
        jLSeleccioneMotor5 = new javax.swing.JLabel();
        jPlinea2 = new javax.swing.JPanel();
        jSpincantModelo2 = new javax.swing.JSpinner();
        jCselectModelo2 = new javax.swing.JComboBox<>();
        jCselectedEjes2 = new javax.swing.JCheckBox();
        jCcantEjes2 = new javax.swing.JComboBox<>();
        jLSeleccioneMotor = new javax.swing.JLabel();
        jPlinea8 = new javax.swing.JPanel();
        jSpinCantModelo8 = new javax.swing.JSpinner();
        jCselectModelo8 = new javax.swing.JComboBox<>();
        jCselectEjes8 = new javax.swing.JCheckBox();
        jCcantEjes8 = new javax.swing.JComboBox<>();
        jLSeleccioneMotor6 = new javax.swing.JLabel();
        jLNombreApp = new javax.swing.JLabel();
        jBLimpiarDat = new javax.swing.JButton();
        jLcant = new javax.swing.JLabel();
        jLtotalUnid = new javax.swing.JLabel();
        jLmodelo = new javax.swing.JLabel();
        jLejeNeum = new javax.swing.JLabel();
        jLmotores = new javax.swing.JLabel();
        jBreporte = new javax.swing.JButton();
        jBagregarCol = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jdPronostico = new com.toedter.calendar.JDateChooser();
        jLimagenApp = new javax.swing.JLabel();
        jMenuProno = new javax.swing.JMenuBar();
        jPanelAgregar = new javax.swing.JMenu();
        mItemAgregarModel = new javax.swing.JMenuItem();
        menuProno = new javax.swing.JMenu();
        mItemNuevoP = new javax.swing.JMenuItem();
        menuConfiguracion = new javax.swing.JMenu();
        mItemConfig = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        mItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pronóstico de Personal");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelImagen.setBackground(new java.awt.Color(255, 255, 255));

        jLimagen.setBackground(new java.awt.Color(255, 255, 255));
        jLimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kenworthsimulator/Kenworth.jpg"))); // NOI18N
        jLimagen.setPreferredSize(new java.awt.Dimension(890, 597));

        javax.swing.GroupLayout jPanelImagenLayout = new javax.swing.GroupLayout(jPanelImagen);
        jPanelImagen.setLayout(jPanelImagenLayout);
        jPanelImagenLayout.setHorizontalGroup(
            jPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenLayout.createSequentialGroup()
                .addComponent(jLimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelImagenLayout.setVerticalGroup(
            jPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenLayout.createSequentialGroup()
                .addComponent(jLimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelImagen);
        jPanelImagen.setBounds(0, 3, 753, 500);

        jPanelPronos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPronos.setPreferredSize(new java.awt.Dimension(800, 572));
        jPanelPronos.setLayout(null);

        jLejes.setBackground(new java.awt.Color(255, 51, 51));
        jLejes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLejes.setText("Cantidad de Ejes");
        jPanelPronos.add(jLejes);
        jLejes.setBounds(480, 90, 110, 15);

        jBvistaPre.setBackground(new java.awt.Color(204, 204, 204));
        jBvistaPre.setText("Vista Previa");
        jBvistaPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvistaPreActionPerformed(evt);
            }
        });
        jPanelPronos.add(jBvistaPre);
        jBvistaPre.setBounds(150, 50, 95, 23);

        jLunidad.setBackground(new java.awt.Color(255, 51, 51));
        jLunidad.setText("0");
        jPanelPronos.add(jLunidad);
        jLunidad.setBounds(120, 50, 6, 14);

        jPejecucionPron.setBackground(new java.awt.Color(255, 255, 255));
        jPejecucionPron.setForeground(new java.awt.Color(255, 255, 255));
        jPejecucionPron.setLayout(null);

        jPlinea3.setBackground(new java.awt.Color(255, 255, 255));
        jPlinea3.setLayout(null);

        jSpinCantModelo3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jSpinCantModelo3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpinCantModelo3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinCantModelo3StateChanged(evt);
            }
        });
        jPlinea3.add(jSpinCantModelo3);
        jSpinCantModelo3.setBounds(140, 10, 50, 20);

        jCselectModelo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCselectModelo3ActionPerformed(evt);
            }
        });
        jPlinea3.add(jCselectModelo3);
        jCselectModelo3.setBounds(10, 6, 110, 30);

        jCselectedEjes3.setBackground(new java.awt.Color(204, 204, 204));
        jPlinea3.add(jCselectedEjes3);
        jCselectedEjes3.setBounds(540, 10, 21, 21);

        jCcantEjes3.setBackground(new java.awt.Color(204, 204, 204));
        jCcantEjes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcantEjes3ActionPerformed(evt);
            }
        });
        jPlinea3.add(jCcantEjes3);
        jCcantEjes3.setBounds(400, 10, 70, 20);

        jLSeleccioneMotor1.setText("selección");
        jPlinea3.add(jLSeleccioneMotor1);
        jLSeleccioneMotor1.setBounds(240, 10, 130, 20);

        jPejecucionPron.add(jPlinea3);
        jPlinea3.setBounds(10, 40, 590, 40);

        jPlinea4.setBackground(new java.awt.Color(255, 255, 255));
        jPlinea4.setLayout(null);

        jSpinCantModelo4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jSpinCantModelo4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpinCantModelo4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinCantModelo4StateChanged(evt);
            }
        });
        jPlinea4.add(jSpinCantModelo4);
        jSpinCantModelo4.setBounds(140, 10, 50, 20);

        jCselectModelo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCselectModelo4ActionPerformed(evt);
            }
        });
        jPlinea4.add(jCselectModelo4);
        jCselectModelo4.setBounds(10, 6, 110, 30);

        jCselectEjes4.setBackground(new java.awt.Color(204, 204, 204));
        jPlinea4.add(jCselectEjes4);
        jCselectEjes4.setBounds(540, 10, 21, 21);

        jCcantEjes4.setBackground(new java.awt.Color(204, 204, 204));
        jCcantEjes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcantEjes4ActionPerformed(evt);
            }
        });
        jPlinea4.add(jCcantEjes4);
        jCcantEjes4.setBounds(400, 10, 70, 20);

        jLSeleccioneMotor2.setText("selección");
        jPlinea4.add(jLSeleccioneMotor2);
        jLSeleccioneMotor2.setBounds(240, 10, 130, 20);

        jPejecucionPron.add(jPlinea4);
        jPlinea4.setBounds(10, 90, 590, 40);

        jPlinea5.setBackground(new java.awt.Color(255, 255, 255));
        jPlinea5.setLayout(null);

        jSpincantModelo5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jSpincantModelo5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpincantModelo5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpincantModelo5StateChanged(evt);
            }
        });
        jPlinea5.add(jSpincantModelo5);
        jSpincantModelo5.setBounds(140, 10, 50, 20);

        jCselectModelo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCselectModelo5ActionPerformed(evt);
            }
        });
        jPlinea5.add(jCselectModelo5);
        jCselectModelo5.setBounds(10, 6, 110, 30);

        jCselectEjes5.setBackground(new java.awt.Color(204, 204, 204));
        jPlinea5.add(jCselectEjes5);
        jCselectEjes5.setBounds(540, 10, 21, 21);

        jCcantEjes5.setBackground(new java.awt.Color(204, 204, 204));
        jCcantEjes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcantEjes5ActionPerformed(evt);
            }
        });
        jPlinea5.add(jCcantEjes5);
        jCcantEjes5.setBounds(400, 10, 70, 20);

        jLSeleccioneMotor3.setText("selección");
        jPlinea5.add(jLSeleccioneMotor3);
        jLSeleccioneMotor3.setBounds(240, 10, 130, 20);

        jPejecucionPron.add(jPlinea5);
        jPlinea5.setBounds(10, 130, 590, 40);

        jPlinea6.setBackground(new java.awt.Color(255, 255, 255));
        jPlinea6.setLayout(null);

        jSpincantModelo6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jSpincantModelo6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpincantModelo6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpincantModelo6StateChanged(evt);
            }
        });
        jPlinea6.add(jSpincantModelo6);
        jSpincantModelo6.setBounds(140, 10, 50, 20);

        jCselectModelo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCselectModelo6ActionPerformed(evt);
            }
        });
        jPlinea6.add(jCselectModelo6);
        jCselectModelo6.setBounds(10, 6, 110, 30);

        jCselectEjes6.setBackground(new java.awt.Color(204, 204, 204));
        jPlinea6.add(jCselectEjes6);
        jCselectEjes6.setBounds(540, 10, 21, 21);

        jCcantEjes6.setBackground(new java.awt.Color(204, 204, 204));
        jCcantEjes6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcantEjes6ActionPerformed(evt);
            }
        });
        jPlinea6.add(jCcantEjes6);
        jCcantEjes6.setBounds(400, 10, 70, 20);

        jLSeleccioneMotor4.setText("selección");
        jPlinea6.add(jLSeleccioneMotor4);
        jLSeleccioneMotor4.setBounds(240, 10, 130, 20);

        jPejecucionPron.add(jPlinea6);
        jPlinea6.setBounds(10, 170, 590, 40);

        jPlinea7.setBackground(new java.awt.Color(255, 255, 255));
        jPlinea7.setLayout(null);

        jSpincantModelo7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jSpincantModelo7.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpincantModelo7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpincantModelo7StateChanged(evt);
            }
        });
        jPlinea7.add(jSpincantModelo7);
        jSpincantModelo7.setBounds(140, 10, 50, 20);

        jCselectModelo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCselectModelo7ActionPerformed(evt);
            }
        });
        jPlinea7.add(jCselectModelo7);
        jCselectModelo7.setBounds(10, 6, 110, 30);

        jCselectEjes7.setBackground(new java.awt.Color(204, 204, 204));
        jCselectEjes7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCselectEjes7ActionPerformed(evt);
            }
        });
        jPlinea7.add(jCselectEjes7);
        jCselectEjes7.setBounds(540, 10, 21, 21);

        jCcantEjes7.setBackground(new java.awt.Color(204, 204, 204));
        jCcantEjes7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcantEjes7ActionPerformed(evt);
            }
        });
        jPlinea7.add(jCcantEjes7);
        jCcantEjes7.setBounds(400, 10, 70, 20);

        jLSeleccioneMotor5.setText("selección");
        jPlinea7.add(jLSeleccioneMotor5);
        jLSeleccioneMotor5.setBounds(240, 10, 130, 20);

        jPejecucionPron.add(jPlinea7);
        jPlinea7.setBounds(10, 210, 590, 40);

        jPlinea2.setBackground(new java.awt.Color(255, 255, 255));
        jPlinea2.setLayout(null);

        jSpincantModelo2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jSpincantModelo2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpincantModelo2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpincantModelo2StateChanged(evt);
            }
        });
        jPlinea2.add(jSpincantModelo2);
        jSpincantModelo2.setBounds(140, 10, 50, 20);

        jCselectModelo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCselectModelo2ActionPerformed(evt);
            }
        });
        jPlinea2.add(jCselectModelo2);
        jCselectModelo2.setBounds(10, 6, 110, 30);

        jCselectedEjes2.setBackground(new java.awt.Color(204, 204, 204));
        jPlinea2.add(jCselectedEjes2);
        jCselectedEjes2.setBounds(540, 10, 21, 21);

        jCcantEjes2.setBackground(new java.awt.Color(204, 204, 204));
        jCcantEjes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcantEjes2ActionPerformed(evt);
            }
        });
        jPlinea2.add(jCcantEjes2);
        jCcantEjes2.setBounds(400, 10, 70, 20);

        jLSeleccioneMotor.setText("selección");
        jPlinea2.add(jLSeleccioneMotor);
        jLSeleccioneMotor.setBounds(240, 10, 130, 20);

        jPejecucionPron.add(jPlinea2);
        jPlinea2.setBounds(10, 0, 590, 40);

        jPlinea8.setBackground(new java.awt.Color(255, 255, 255));
        jPlinea8.setLayout(null);

        jSpinCantModelo8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jSpinCantModelo8.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpinCantModelo8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinCantModelo8StateChanged(evt);
            }
        });
        jPlinea8.add(jSpinCantModelo8);
        jSpinCantModelo8.setBounds(140, 10, 50, 20);

        jCselectModelo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCselectModelo8ActionPerformed(evt);
            }
        });
        jPlinea8.add(jCselectModelo8);
        jCselectModelo8.setBounds(10, 6, 110, 30);

        jCselectEjes8.setBackground(new java.awt.Color(204, 204, 204));
        jPlinea8.add(jCselectEjes8);
        jCselectEjes8.setBounds(540, 10, 21, 21);

        jCcantEjes8.setBackground(new java.awt.Color(204, 204, 204));
        jCcantEjes8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcantEjes8ActionPerformed(evt);
            }
        });
        jPlinea8.add(jCcantEjes8);
        jCcantEjes8.setBounds(400, 10, 70, 20);

        jLSeleccioneMotor6.setText("selección");
        jPlinea8.add(jLSeleccioneMotor6);
        jLSeleccioneMotor6.setBounds(240, 10, 130, 20);

        jPejecucionPron.add(jPlinea8);
        jPlinea8.setBounds(10, 250, 590, 40);

        jPanelPronos.add(jPejecucionPron);
        jPejecucionPron.setBounds(90, 110, 640, 300);

        jLNombreApp.setBackground(new java.awt.Color(255, 51, 51));
        jLNombreApp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLNombreApp.setForeground(new java.awt.Color(0, 51, 51));
        jLNombreApp.setText("Pronóstico de Personal");
        jPanelPronos.add(jLNombreApp);
        jLNombreApp.setBounds(260, 10, 294, 33);

        jBLimpiarDat.setBackground(new java.awt.Color(204, 204, 204));
        jBLimpiarDat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBLimpiarDat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LIMPIAR.jpg"))); // NOI18N
        jBLimpiarDat.setText("Limpiar datos");
        jBLimpiarDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarDatActionPerformed(evt);
            }
        });
        jPanelPronos.add(jBLimpiarDat);
        jBLimpiarDat.setBounds(530, 430, 150, 40);

        jLcant.setBackground(new java.awt.Color(255, 51, 51));
        jLcant.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLcant.setText("Cantidad");
        jPanelPronos.add(jLcant);
        jLcant.setBounds(240, 90, 70, 15);

        jLtotalUnid.setBackground(new java.awt.Color(255, 51, 51));
        jLtotalUnid.setText("Total de unidades");
        jPanelPronos.add(jLtotalUnid);
        jLtotalUnid.setBounds(90, 20, 85, 14);

        jLmodelo.setBackground(new java.awt.Color(255, 51, 51));
        jLmodelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLmodelo.setText("Modelo");
        jPanelPronos.add(jLmodelo);
        jLmodelo.setBounds(120, 90, 50, 15);

        jLejeNeum.setBackground(new java.awt.Color(255, 51, 51));
        jLejeNeum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLejeNeum.setText("Eje neumático");
        jPanelPronos.add(jLejeNeum);
        jLejeNeum.setBounds(610, 90, 90, 15);

        jLmotores.setBackground(new java.awt.Color(255, 51, 51));
        jLmotores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLmotores.setText("Motores");
        jPanelPronos.add(jLmotores);
        jLmotores.setBounds(340, 90, 80, 15);

        jBreporte.setBackground(new java.awt.Color(204, 204, 204));
        jBreporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/REPORTES.jpg"))); // NOI18N
        jBreporte.setText("Reporte");
        jBreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBreporteActionPerformed(evt);
            }
        });
        jPanelPronos.add(jBreporte);
        jBreporte.setBounds(330, 430, 130, 40);

        jBagregarCol.setBackground(new java.awt.Color(204, 204, 204));
        jBagregarCol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBagregarCol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/increase.png"))); // NOI18N
        jBagregarCol.setText("Agregar");
        jBagregarCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarColActionPerformed(evt);
            }
        });
        jPanelPronos.add(jBagregarCol);
        jBagregarCol.setBounds(110, 430, 130, 40);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Fecha de Pronóstico:");
        jPanelPronos.add(jLabel1);
        jLabel1.setBounds(270, 50, 127, 30);

        jdPronostico.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPronos.add(jdPronostico);
        jdPronostico.setBounds(390, 50, 130, 30);

        jLimagenApp.setBackground(new java.awt.Color(255, 255, 255));
        jLimagenApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo_1.jpg"))); // NOI18N
        jPanelPronos.add(jLimagenApp);
        jLimagenApp.setBounds(0, 0, 100, 120);

        getContentPane().add(jPanelPronos);
        jPanelPronos.setBounds(0, 1, 770, 500);

        jMenuProno.setBackground(new java.awt.Color(255, 255, 255));

        jPanelAgregar.setText("Agregar");

        mItemAgregarModel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mItemAgregarModel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/increase.png"))); // NOI18N
        mItemAgregarModel.setText("Agregar Modelo");
        mItemAgregarModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAgregarModelActionPerformed(evt);
            }
        });
        jPanelAgregar.add(mItemAgregarModel);

        jMenuProno.add(jPanelAgregar);

        menuProno.setText("Pronóstico");

        mItemNuevoP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mItemNuevoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HOJA.jpg"))); // NOI18N
        mItemNuevoP.setText("Nuevo Pronóstico");
        mItemNuevoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemNuevoPActionPerformed(evt);
            }
        });
        menuProno.add(mItemNuevoP);

        jMenuProno.add(menuProno);

        menuConfiguracion.setText("Configuración");

        mItemConfig.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        mItemConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/engrane.png"))); // NOI18N
        mItemConfig.setText("Modificar Parámetros");
        mItemConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemConfigActionPerformed(evt);
            }
        });
        menuConfiguracion.add(mItemConfig);

        jMenuProno.add(menuConfiguracion);

        menuSalir.setText("Salir");

        mItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salida.png"))); // NOI18N
        mItemSalir.setText("Salida");
        mItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSalirActionPerformed(evt);
            }
        });
        menuSalir.add(mItemSalir);

        jMenuProno.add(menuSalir);

        setJMenuBar(jMenuProno);

        setBounds(0, 0, 766, 558);
    }// </editor-fold>//GEN-END:initComponents

    private void mItemNuevoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemNuevoPActionPerformed
        jPanelImagen.setVisible(false);//oculta el panel principal
        jPanelPronos.setVisible(true);//habilita el panel del pronostico
        jLtotalUnid.setVisible(false);
        jLunidad.setVisible(false);
        jBLimpiarDat.setVisible(true);
        jBvistaPre.setVisible(false);
        
    }//GEN-LAST:event_mItemNuevoPActionPerformed

    private void mItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mItemSalirActionPerformed

    private void mItemAgregarModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAgregarModelActionPerformed
        // TODO add your handling code here:
        jPanelPronos.setVisible(false);
        jPanelImagen.setVisible(false);
        jDagregarModel mod = new jDagregarModel(this, true);
        mod.setVisible(true);
    }//GEN-LAST:event_mItemAgregarModelActionPerformed

    private void mItemConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemConfigActionPerformed
        // TODO add your handling code here:
        jPanelPronos.setVisible(false);
        jPanelImagen.setVisible(false);
        jDconfiguracion conf = new jDconfiguracion(this, true);
        conf.setVisible(true);
    }//GEN-LAST:event_mItemConfigActionPerformed

    private void jBagregarColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarColActionPerformed
        // TODO add your handling code here:
       // if (jdPronostico.getDate() > getDate()){
       //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        if (veces == 1 ){
            veces++;
            jCselectModelo2.addItem("seleccioné");
            jCselectModelo3.addItem("seleccioné");
            jCselectModelo4.addItem("seleccioné");
            jCselectModelo5.addItem("seleccioné");
            jCselectModelo6.addItem("seleccioné");
            jCselectModelo7.addItem("seleccioné");
            jCselectModelo8.addItem("seleccioné");
            for (int i = 0; i < modelos.size(); i++) {                
                jCselectModelo2.addItem(modelos.get(i));
                jCselectModelo3.addItem(modelos.get(i));
                jCselectModelo4.addItem(modelos.get(i));
                jCselectModelo5.addItem(modelos.get(i));
                jCselectModelo6.addItem(modelos.get(i));
                jCselectModelo7.addItem(modelos.get(i));
                jCselectModelo8.addItem(modelos.get(i));
            }
        }
        if (cont == 0) {//agrega una linea al pronostico
            jPlinea2.setVisible(true);
            jSpincantModelo2.setEnabled(false);// deshabilita el spiner de modelo de una linea
            jCcantEjes2.setEnabled(false);
            //jCmotor2.setEnabled(false);//deshabilita la seleccion de motor
            jCselectedEjes2.setEnabled(false);//deshabilitala opcion de seleccionar eje neumatico
            jPlinea3.setVisible(false);
            jPlinea4.setVisible(false);
            jPlinea5.setVisible(false);
            jPlinea6.setVisible(false);
            jPlinea7.setVisible(false);
            jPlinea8.setVisible(false);
            cont++;
            val = false;
        } else if ((cont == 1) && (val == true)) {
            jSpinCantModelo3.setEnabled(false);
            jCcantEjes3.setEnabled(false);
            jCselectedEjes3.setEnabled(false);
            jPlinea2.setVisible(true);
            jPlinea3.setVisible(true);
            jPlinea4.setVisible(false);
            jPlinea5.setVisible(false);
            jPlinea6.setVisible(false);
            jPlinea7.setVisible(false);
            jPlinea8.setVisible(false);
            cont++;
        } else if ((cont == 2) && (val == true)) {
            jSpinCantModelo4.setEnabled(false);
            jCcantEjes4.setEnabled(false);
            jCselectEjes4.setEnabled(false);
            jPlinea2.setVisible(true);
            jPlinea3.setVisible(true);
            jPlinea4.setVisible(true);
            jPlinea5.setVisible(false);
            jPlinea6.setVisible(false);
            jPlinea7.setVisible(false);
            jPlinea8.setVisible(false);
            String var = jSpinCantModelo4.getValue().toString();
            total = total + Integer.parseInt(var);
            cont++;
        } else if ((cont == 3) && (val == true)) {
            jSpincantModelo5.setEnabled(false);
            jCselectEjes5.setEnabled(false);
            jCcantEjes5.setEnabled(false);
            jPlinea2.setVisible(true);
            jPlinea3.setVisible(true);
            jPlinea4.setVisible(true);
            jPlinea5.setVisible(true);
            jPlinea6.setVisible(false);
            jPlinea7.setVisible(false);
            jPlinea8.setVisible(false);
            String var = jSpincantModelo5.getValue().toString();
            total = total + Integer.parseInt(var);
            cont++;
        } else if ((cont == 4) && (val == true)) {
            jSpincantModelo6.setEnabled(false);
            jCselectEjes6.setEnabled(false);
            jCcantEjes6.setEnabled(false);
            jPlinea2.setVisible(true);
            jPlinea3.setVisible(true);
            jPlinea4.setVisible(true);
            jPlinea5.setVisible(true);
            jPlinea6.setVisible(true);
            jPlinea7.setVisible(false);
            jPlinea8.setVisible(false);
            String var = jSpincantModelo6.getValue().toString();
            total = total + Integer.parseInt(var);
            cont++;
        } else if ((cont == 5) && (val == true)) {
            jCcantEjes7.setEnabled(false);
            jSpincantModelo7.setEnabled(false);
            jCselectEjes7.setEnabled(false);
            jPlinea2.setVisible(true);
            jPlinea3.setVisible(true);
            jPlinea4.setVisible(true);
            jPlinea5.setVisible(true);
            jPlinea6.setVisible(true);
            jPlinea7.setVisible(true);
            jPlinea8.setVisible(false);
            String var = jSpincantModelo7.getValue().toString();
            total = total + Integer.parseInt(var);
            cont++;
        } else if ((cont == 6) && (val == true)) {
            jCcantEjes8.setEnabled(false);
            jSpinCantModelo8.setEnabled(false);
            jCselectEjes8.setEnabled(false);
            jPlinea2.setVisible(true);
            jPlinea3.setVisible(true);
            jPlinea4.setVisible(true);
            jPlinea5.setVisible(true);
            jPlinea6.setVisible(true);
            jPlinea7.setVisible(true);
            jPlinea8.setVisible(true);
            String var = jSpinCantModelo8.getValue().toString();
            total = total + Integer.parseInt(var);
            cont++;
        } else if ((cont == 7) && (val == true)) {

            jPlinea2.setVisible(true);
            jPlinea3.setVisible(true);
            jPlinea4.setVisible(true);
            jPlinea5.setVisible(true);
            jPlinea6.setVisible(true);
            jPlinea7.setVisible(true);
            jPlinea8.setVisible(true);
            cont++;
        } else if ((cont == 8) && (val == true)) {
            jPlinea2.setVisible(true);
            jPlinea3.setVisible(true);
            jPlinea4.setVisible(true);
            jPlinea5.setVisible(true);
            jPlinea6.setVisible(true);
            jPlinea7.setVisible(true);
            jPlinea8.setVisible(true);
            cont++;
        } else if ((cont == 9) && (val == true)) {
            cont++;
            jPlinea2.setVisible(true);
            jPlinea3.setVisible(true);
            jPlinea4.setVisible(true);
            jPlinea5.setVisible(true);
            jPlinea6.setVisible(true);
            jPlinea7.setVisible(true);
            jPlinea8.setVisible(true);
        }
    }//GEN-LAST:event_jBagregarColActionPerformed

    private void jCcantEjes8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcantEjes8ActionPerformed
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCcantEjes8.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            jCselectEjes8.setEnabled(true);
            val = true;
        }//fin del if
    }//GEN-LAST:event_jCcantEjes8ActionPerformed

    private void jCselectModelo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCselectModelo8ActionPerformed
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCselectModelo8.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            try {
                ModelId = jCselectModelo8.getSelectedItem().toString();
                modelengine = db.readmodelengine(ModelId);
                jLSeleccioneMotor6.setText(db.readmodelengine(ModelId));
                jSpinCantModelo8.setEnabled(true);
                CantEjes = db.tiempodeejes(ModelId);
                jCcantEjes8.removeAllItems();         
                for (int i = 0; i < CantEjes.size(); i++) {                    
                    String tmp = CantEjes.get(i).toString();                    
                    jCcantEjes8.addItem(tmp);
                    val = false;
                }
            } catch (SQLException ex) {
                Logger.getLogger(KenworthPronostico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jCselectModelo8ActionPerformed

    private void jSpinCantModelo8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinCantModelo8StateChanged
        // TODO add your handling code here:
        String change = "";
        jLunidad.setText("");
        change = "" + jSpinCantModelo8.getValue();
        if (change != "0") {
            jCcantEjes8.setEnabled(true);
            totaldeunidades();
           // jLunidad.setText("" + total);
            val = false;
        }
    }//GEN-LAST:event_jSpinCantModelo8StateChanged

    private void jCcantEjes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcantEjes2ActionPerformed
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCcantEjes2.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            jCselectedEjes2.setEnabled(true);
            val = true;
        }
    }//GEN-LAST:event_jCcantEjes2ActionPerformed

    private void jCselectModelo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCselectModelo2ActionPerformed
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCselectModelo2.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            try {
                ModelId = jCselectModelo2.getSelectedItem().toString();
                modelengine = db.readmodelengine(ModelId);
                jLSeleccioneMotor.setText(db.readmodelengine(ModelId));
                jSpincantModelo2.setEnabled(true);
                CantEjes = db.tiempodeejes(ModelId);
                jCcantEjes2.removeAllItems();         
                for (int i = 0; i < CantEjes.size(); i++) {                    
                    String tmp = CantEjes.get(i).toString();                    
                    jCcantEjes2.addItem(tmp);
                    val = false;
                }
            } catch (SQLException ex) {
                Logger.getLogger(KenworthPronostico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jCselectModelo2ActionPerformed

    private void jSpincantModelo2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpincantModelo2StateChanged
        // TODO add your handling code here:
        String change = "";        
        int valor = 0;
        // jLunidad.setText("");
        change = "" + jSpincantModelo2.getValue();
        valor = Integer.parseInt(change);
        if (valor > 0 && valor <= 100) {
            if (change != "0") {
                jCcantEjes2.setEnabled(true);
                String valorTemp = jSpincantModelo2.getValue().toString();
                total = Integer.parseInt(valorTemp);
                //jLunidad.setText("" + total);
                totaldeunidades();
                val = false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "No puede ingresar 0 como cantidad tiene un rango de 1 a 100");
        }
    }//GEN-LAST:event_jSpincantModelo2StateChanged

    private void jCcantEjes7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcantEjes7ActionPerformed
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCcantEjes7.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            jCselectEjes7.setEnabled(true);
            val = true;
        }//fin del if
    }//GEN-LAST:event_jCcantEjes7ActionPerformed

    private void jCselectModelo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCselectModelo7ActionPerformed
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCselectModelo7.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            try {
                ModelId = jCselectModelo7.getSelectedItem().toString();
                modelengine = db.readmodelengine(ModelId);
                jLSeleccioneMotor5.setText(db.readmodelengine(ModelId));
                jSpincantModelo7.setEnabled(true);
                CantEjes = db.tiempodeejes(ModelId);
                jCcantEjes7.removeAllItems();
                System.out.println("Cant ejes " + CantEjes);
                for (int i = 0; i < CantEjes.size(); i++) {                    
                    String tmp = CantEjes.get(i).toString();                    
                    jCcantEjes7.addItem(tmp);
                    val = false;
                }
            } catch (SQLException ex) {
                Logger.getLogger(KenworthPronostico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jCselectModelo7ActionPerformed

    private void jSpincantModelo7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpincantModelo7StateChanged
        // TODO add your handling code here:
        String change = "";
        jLunidad.setText("");
        change = "" + jSpincantModelo7.getValue();
        if (change != "0") {
            jCcantEjes7.setEnabled(true);
            totaldeunidades();
           // jLunidad.setText("" + total);
            val = false;
        }
    }//GEN-LAST:event_jSpincantModelo7StateChanged

    private void jCcantEjes6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcantEjes6ActionPerformed
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCcantEjes6.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            jCselectEjes6.setEnabled(true);
            val = true;
        }//fin del if
    }//GEN-LAST:event_jCcantEjes6ActionPerformed

    private void jCselectModelo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCselectModelo6ActionPerformed
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCselectModelo6.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            try {
                ModelId = jCselectModelo6.getSelectedItem().toString();
                modelengine = db.readmodelengine(ModelId);
                jLSeleccioneMotor4.setText(db.readmodelengine(ModelId));
                jSpincantModelo6.setEnabled(true);
                CantEjes = db.tiempodeejes(ModelId);
                jCcantEjes6.removeAllItems();
                System.out.println("Cant ejes " + CantEjes);
                for (int i = 0; i < CantEjes.size(); i++) {                    
                    String tmp = CantEjes.get(i).toString();                    
                    jCcantEjes6.addItem(tmp);
                    val = false;
                }
            } catch (SQLException ex) {
                Logger.getLogger(KenworthPronostico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jCselectModelo6ActionPerformed

    private void jSpincantModelo6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpincantModelo6StateChanged
        // TODO add your handling code here:
        String change = "";
        jLunidad.setText("" + total);
        change = "" + jSpincantModelo6.getValue();
        if (change != "0") {
            jCcantEjes6.setEnabled(true);
            totaldeunidades();
           // jLunidad.setText("" + total);
            val = false;
        }
    }//GEN-LAST:event_jSpincantModelo6StateChanged

    private void jCcantEjes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcantEjes5ActionPerformed
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCcantEjes5.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            jCselectEjes5.setEnabled(true);
            val = true;
        }//fin del if
    }//GEN-LAST:event_jCcantEjes5ActionPerformed

    private void jCselectModelo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCselectModelo5ActionPerformed
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCselectModelo5.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            try {
                ModelId = jCselectModelo5.getSelectedItem().toString();
                modelengine = db.readmodelengine(ModelId);
                jLSeleccioneMotor3.setText(db.readmodelengine(ModelId));
                jSpincantModelo5.setEnabled(true);
                CantEjes = db.tiempodeejes(ModelId);
                jCcantEjes5.removeAllItems();
                //System.out.println("Cant ejes " + CantEjes);
                for (int i = 0; i < CantEjes.size(); i++) {
                    //jCcantEjes2.addItem(CantEjes.get(i));
                    String tmp = CantEjes.get(i).toString();                    
                    jCcantEjes5.addItem(tmp);
                    val = false;
                }
            } catch (SQLException ex) {
                Logger.getLogger(KenworthPronostico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jCselectModelo5ActionPerformed

    private void jSpincantModelo5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpincantModelo5StateChanged
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        jLunidad.setText("");
        change = "" + jSpincantModelo5.getValue();
        if (!change.equalsIgnoreCase("seleccioné")) {
            jCcantEjes5.setEnabled(true);
            totaldeunidades();
            //jLunidad.setText("" + total);
            val = false;
        }
    }//GEN-LAST:event_jSpincantModelo5StateChanged

    private void jCcantEjes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcantEjes4ActionPerformed
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCcantEjes4.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            jCselectEjes4.setEnabled(true);
            val = true;
        }//fin del if
    }//GEN-LAST:event_jCcantEjes4ActionPerformed

    private void jCselectModelo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCselectModelo4ActionPerformed
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCselectModelo4.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            try {
                ModelId = jCselectModelo4.getSelectedItem().toString();
                modelengine = db.readmodelengine(ModelId);
                jLSeleccioneMotor2.setText(db.readmodelengine(ModelId));
                jSpinCantModelo4.setEnabled(true);
                CantEjes = db.tiempodeejes(ModelId);
                jCcantEjes4.removeAllItems();
                System.out.println("Cant ejes " + CantEjes);
                for (int i = 0; i < CantEjes.size(); i++) {
                    //jCcantEjes2.addItem(CantEjes.get(i));
                    String tmp = CantEjes.get(i).toString();                    
                    jCcantEjes4.addItem(tmp);
                    val = false;
                }
            } catch (SQLException ex) {
                Logger.getLogger(KenworthPronostico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jCselectModelo4ActionPerformed

    private void jSpinCantModelo4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinCantModelo4StateChanged
        // TODO add your handling code here:
        String change = "";
        jLunidad.setText("" + total);
        jLunidad.setText("");
        change = "" + jSpinCantModelo4.getValue();
        if (change != "0") {
            jCcantEjes4.setEnabled(true);
            totaldeunidades();
           // jLunidad.setText("" + total);
            val = false;
        }

    }//GEN-LAST:event_jSpinCantModelo4StateChanged

    private void jCcantEjes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcantEjes3ActionPerformed
        // TODO add your handling code here:
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCcantEjes3.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            jCselectedEjes3.setEnabled(true);
            val = true;
        }//fin del if
    }//GEN-LAST:event_jCcantEjes3ActionPerformed

    private void jCselectModelo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCselectModelo3ActionPerformed
        // TODO add your handling code here:        
        //se cambio la ortografia 25 de noviembre 2019 Edgar Torres
        String change = "";
        change = "" + jCselectModelo3.getSelectedItem();
        if (!change.equalsIgnoreCase("seleccioné")) {
            try {
                ModelId = jCselectModelo3.getSelectedItem().toString();
                modelengine = db.readmodelengine(ModelId);
                jLSeleccioneMotor1.setText(db.readmodelengine(ModelId));
                jSpinCantModelo3.setEnabled(true);
                CantEjes = db.tiempodeejes(ModelId);
                jCcantEjes3.removeAllItems();
                System.out.println("Cant ejes " + CantEjes);
                for (int i = 0; i < CantEjes.size(); i++) {                    
                    String tmp = CantEjes.get(i).toString();                    
                    jCcantEjes3.addItem(tmp);
                    val = false;
                }
            } catch (SQLException ex) {
                Logger.getLogger(KenworthPronostico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jCselectModelo3ActionPerformed

    private void jSpinCantModelo3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinCantModelo3StateChanged
        // TODO add your handling code here:
        String change = "";
        //jLunidad.setText("");
        change = "" + jSpinCantModelo3.getValue();
        if (change != "0") {
            jCcantEjes3.setEnabled(true);
            String valorTemp = jSpinCantModelo3.getValue().toString();
            total = total + Integer.parseInt(valorTemp);
        //    jLunidad.setText("" + total);
            totaldeunidades();
            val = false;
        }
    }//GEN-LAST:event_jSpinCantModelo3StateChanged

    private void jBvistaPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvistaPreActionPerformed
        // TODO add your handling code here:        
        //vista.lbReporteModelo1.setText(pr.modelos());
        allfunctions();
        vista.setVisible(true);
    }//GEN-LAST:event_jBvistaPreActionPerformed
    private void allfunctions(){
        limpiaetiquetas();
        llenarcamposmodelos();
        llenarcamposcantidad();
        llenarcamposmotores();
        llenarcamposejes();
        llenarcamposEnemumatico();
        fechapronostico();
        try {        
            calculosnegocio();
        } catch (SQLException ex) {
            Logger.getLogger(KenworthPronostico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jBreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreporteActionPerformed
        try {
            allfunctions();           
            JasperReport RP = (JasperReport)JRLoader.loadObject(KenworthPronostico.class.getResource("/Reportes/ReportePronostico.jasper"));
            Map datos = new  HashMap();                        
            datos.put("M01", vista.lbReporteModelo1.getText());datos.put("M02", vista.lbReporteModelo2.getText());
            datos.put("M03", vista.lbReporteModelo3.getText());datos.put("M04", vista.lbReporteModelo4.getText());
            datos.put("M05", vista.lbReporteModelo5.getText());datos.put("M06", vista.lbReporteModelo6.getText());
            datos.put("M07", vista.lbReporteModelo7.getText());
            
            datos.put("CA1", vista.lbReporteCantidad1.getText());datos.put("CA2", vista.lbReporteCantidad2.getText());
            datos.put("CA3", vista.lbReporteCantidad3.getText());datos.put("CA4", vista.lbReporteCantidad4.getText());
            datos.put("CA5", vista.lbReporteCantidad5.getText());datos.put("CA6", vista.lbReporteCantidad6.getText());
            datos.put("CA7", vista.lbReporteCantidad7.getText());datos.put("CTOT", jLunidad.getText());
            
            datos.put("MO1", vista.lbReporteMotor1.getText());datos.put("MO2", vista.lbReporteMotor2.getText());
            datos.put("MO3", vista.lbReporteMotor3.getText());datos.put("MO4", vista.lbReporteMotor4.getText());
            datos.put("MO5", vista.lbReporteMotor5.getText());datos.put("MO6", vista.lbReporteMotor6.getText());
            datos.put("MO7", vista.lbReporteMotor7.getText());
            
            datos.put("EJ1", vista.lbReporteEjes1.getText());datos.put("EJ2", vista.lbReporteEjes2.getText());
            datos.put("EJ3", vista.lbReporteEjes3.getText());datos.put("EJ4", vista.lbReporteEjes4.getText());
            datos.put("EJ5", vista.lbReporteEjes5.getText());datos.put("EJ6", vista.lbReporteEjes6.getText());
            datos.put("EJ7", vista.lbReporteEjes7.getText());
            
            datos.put("EN1", vista.lbReporteEjesN1.getText());datos.put("EN2", vista.lbReporteEjesN2.getText());
            datos.put("EN3", vista.lbReporteEjesN3.getText());datos.put("EN4", vista.lbReporteEjesN4.getText());
            datos.put("EN5", vista.lbReporteEjesN5.getText());datos.put("EN6", vista.lbReporteEjesN6.getText());
            datos.put("EN7", vista.lbReporteEjesN7.getText());
            datos.put("FechaEjecucion", vista.jLfechaEjec.getText());
            datos.put("FechaPronostico", vista.jlReporteFPronostico.getText());
            datos.put("RHAM", vista.jLcantMotorAct.getText());
            datos.put("RHAE", vista.jLcantEjesAct.getText());
            datos.put("RHRM", vista.jLcantMotorReq.getText());
            datos.put("RHRE", vista.jLcantEjesReq.getText());
            datos.put("VacM", vista.jLvacacionesMotor.getText());
            datos.put("VacE", vista.jLvacacionesEJes.getText());
            datos.put("JubM", vista.jLJubilacionesMotor.getText());
            datos.put("JubE",vista.jLJubilacionesEje.getText());
            datos.put("ProduccionActual",vista.jLproduccion.getText());
            datos.put("CapacidadPlanta",vista.jLcapacidadPlanta.getText());
            
            JasperPrint jasperPP = JasperFillManager.fillReport(RP, datos, new JREmptyDataSource());
            JasperViewer jv = new JasperViewer(jasperPP,false);
            jv.show();            
        } catch (JRException ex) {
            Logger.getLogger(KenworthPronostico.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NullPointerException ex){
            //se agrego una excepcion para mandar mensaje en caso que tenga datos incompletos 25 de noviembre 2019 Edgar Torres
            JOptionPane.showMessageDialog(null, "Faltan datos de ingresar....");
        }
        
    }//GEN-LAST:event_jBreporteActionPerformed

    private void jBLimpiarDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarDatActionPerformed
        // TODO add your handling code here:
        //se modifica el boton de limpiar datos 25 de noviembre del 2019 Edgar Torres.
        jPlinea2.setVisible(false);
        jPlinea3.setVisible(false);
        jPlinea4.setVisible(false);
        jPlinea5.setVisible(false);
        jPlinea6.setVisible(false);
        jPlinea7.setVisible(false);
        jPlinea8.setVisible(false);
        cont=0; val=false;
        jSpincantModelo2.setValue(0);
        jCselectedEjes2 =new JCheckBox();
        jSpinCantModelo3.setValue(0);
        jCselectedEjes3.setSelected(false);
        jSpinCantModelo4.setValue(0);
        jCselectEjes4.setSelected(false);
        jSpincantModelo5.setValue(0);
        jCselectEjes5.setSelected(false);
        jSpincantModelo6.setValue(0);
        jCselectEjes6.setSelected(false);
        jSpincantModelo7.setValue(0);
        jCselectEjes7.setSelected(false);
        jSpinCantModelo8.setValue(0);
        jCselectEjes8.setSelected(false);
    }//GEN-LAST:event_jBLimpiarDatActionPerformed

    private void jCselectEjes7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCselectEjes7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCselectEjes7ActionPerformed
    // Calculos de la capa de negocio
    public void calculosnegocio() throws SQLException{        
        vista.jLcantMotorAct.setText(pr.empleadospordepto(30));
        vista.jLcantEjesAct.setText(pr.empleadospordepto(40));        
        // Cantidad de jubilados MOTES/EJES de acuerdo a la fecha ingesada
        String fecha = sdf.format(jdPronostico.getDate());
        vista.jLJubilacionesMotor.setText(pr.jubilados(fecha, 40));
        vista.jLJubilacionesEje.setText(pr.jubilados(fecha, 30));   
        //Vacaciones Motores / Ejes
        vista.jLvacacionesMotor.setText(pr.vacaciones(fecha, 40));
        vista.jLvacacionesEJes.setText(pr.vacaciones(fecha, 30));
        try {
            vista.jLcapacidadPlanta.setText(pr.ReadParameters(1));
        } catch (SQLException ex) {
            Logger.getLogger(KenworthPronostico.class.getName()).log(Level.SEVERE, null, ex);
        }
        vista.jLproduccion.setText(pr.ReadParameters(2));
        
        int cpro, cejes;
        //Double TotEjes, TotMot;
        String Neumatico, mo;
        String Totpersonalmotores, Totpersonalejes;
        
        // Linea numero 1
        mo = jCselectModelo2.getSelectedItem().toString();
        cpro = (int) jSpincantModelo2.getValue();
        cejes = Integer.parseInt(jCcantEjes2.getSelectedItem().toString());        
        Neumatico = vista.lbReporteEjesN1.getText();
        
        TotMot = (pr.recursospordeptomotores(mo, cpro));
        TotEjes = (pr.recursospordeptoejes(mo, cejes, cpro, Neumatico));
        //System.out.println("Motores 1 " + TotMot);
         // Linea numero 2
        if(jCselectModelo3.getSelectedIndex() > 0){
            if (((int)jSpinCantModelo3.getValue()) > 0) {
                mo = jCselectModelo3.getSelectedItem().toString();
                cpro = (int) jSpinCantModelo3.getValue(); 
                cejes = Integer.parseInt(jCcantEjes3.getSelectedItem().toString());
                Neumatico = vista.lbReporteEjesN2.getText();
                
                TotMot = TotMot + (pr.recursospordeptomotores(mo, cpro));
                TotEjes = TotEjes + (pr.recursospordeptoejes(mo, cejes, cpro, Neumatico));
                //System.out.println("Motores 2 " + TotMot);
            }
        }
        // Linea numero 3
        if(jCselectModelo4.getSelectedIndex() > 0){
            if (((int)jSpinCantModelo4.getValue()) > 0) {
                mo = jCselectModelo4.getSelectedItem().toString();
                cpro = (int) jSpinCantModelo4.getValue(); 
                cejes = Integer.parseInt(jCcantEjes4.getSelectedItem().toString());
                Neumatico = vista.lbReporteEjesN3.getText();
                
                TotMot = TotMot + (pr.recursospordeptomotores(mo, cpro));
                TotEjes = TotEjes + (pr.recursospordeptoejes(mo, cejes, cpro, Neumatico));
                //System.out.println("Motores 3 " + TotMot);
            }
        }
        // Linea numero 4
        if(jCselectModelo5.getSelectedIndex() > 0){
            if (((int)jSpincantModelo5.getValue()) > 0) {
                mo = jCselectModelo5.getSelectedItem().toString();
                cpro = (int) jSpincantModelo5.getValue(); 
                cejes = Integer.parseInt(jCcantEjes5.getSelectedItem().toString());
                Neumatico = vista.lbReporteEjesN4.getText();
                
                TotMot = TotMot + (pr.recursospordeptomotores(mo, cpro));
                TotEjes = TotEjes + (pr.recursospordeptoejes(mo, cejes, cpro, Neumatico));
                //System.out.println("Motores 4 " + TotMot);
            }
        }
        // Linea numero 5
        if(jCselectModelo6.getSelectedIndex() > 0){
            if (((int)jSpincantModelo6.getValue()) > 0) {
                mo = jCselectModelo6.getSelectedItem().toString();
                cpro = (int) jSpincantModelo6.getValue(); 
                cejes = Integer.parseInt(jCcantEjes6.getSelectedItem().toString());
                Neumatico = vista.lbReporteEjesN5.getText();
                
                TotMot = TotMot + (pr.recursospordeptomotores(mo, cpro));
                TotEjes = TotEjes + (pr.recursospordeptoejes(mo, cejes, cpro, Neumatico));
            }
        }
        // Linea numero 6
        if(jCselectModelo7.getSelectedIndex() > 0){
            if (((int)jSpincantModelo7.getValue()) > 0) {
                mo = jCselectModelo7.getSelectedItem().toString();
                cpro = (int) jSpincantModelo7.getValue(); 
                cejes = Integer.parseInt(jCcantEjes7.getSelectedItem().toString());
                Neumatico = vista.lbReporteEjesN6.getText();
                
                TotMot = TotMot + (pr.recursospordeptomotores(mo, cpro));
                TotEjes = TotEjes + (pr.recursospordeptoejes(mo, cejes, cpro, Neumatico));
            }
        }
        // Linea numero 7
        if(jCselectModelo8.getSelectedIndex() > 0){
            if (((int)jSpinCantModelo8.getValue()) > 0) {
                mo = jCselectModelo8.getSelectedItem().toString();
                cpro = (int) jSpinCantModelo8.getValue(); 
                cejes = Integer.parseInt(jCcantEjes8.getSelectedItem().toString());
                Neumatico = vista.lbReporteEjesN7.getText();
                
                TotMot = TotMot + (pr.recursospordeptomotores(mo, cpro));
                TotEjes = TotEjes + (pr.recursospordeptoejes(mo, cejes, cpro, Neumatico));
            }
        }
        int TE = (int)Math.ceil(TotEjes);
        int TM = (int)Math.ceil(TotEjes);
        Totpersonalejes = Integer.toString(TE);
        Totpersonalmotores = Integer.toString(TM);
        
        int permot = Integer.parseInt(vista.jLcantMotorAct.getText());
        int perejes = Integer.parseInt(vista.jLcantEjesAct.getText());        
        permot = TM - permot;
        perejes = TE - perejes;
        vista.lbdifEjes.setText(Integer.toString(perejes));
        vista.lbdifMotores.setText(Integer.toString(permot));
        vista.jLcantEjesReq.setText(Totpersonalejes);
        vista.jLcantMotorReq.setText(Totpersonalmotores);
    }
    // Fecha del pronostico
    public void fechapronostico(){        
        String fecha = sdf.format(jdPronostico.getDate());
        vista.jlReporteFPronostico.setText(fecha);
        Date date = new java.util.Date();  
        String hoy = sdf.format(date);
        vista.jLfechaEjec.setText(hoy);
    }
    // Limpiar variables
    public void limpiaetiquetas(){
        vista.lbReporteModelo1.setText(""); vista.lbReporteModelo2.setText("");
        vista.lbReporteModelo3.setText(""); vista.lbReporteModelo4.setText("");
        vista.lbReporteModelo5.setText(""); vista.lbReporteModelo6.setText("");
        vista.lbReporteModelo7.setText("");
        vista.lbReporteCantidad1.setText(""); vista.lbReporteCantidad2.setText("");
        vista.lbReporteCantidad3.setText(""); vista.lbReporteCantidad4.setText("");
        vista.lbReporteCantidad5.setText(""); vista.lbReporteCantidad6.setText("");
        vista.lbReporteCantidad7.setText("");
        vista.lbReporteMotor1.setText(""); vista.lbReporteMotor2.setText("");
        vista.lbReporteMotor3.setText(""); vista.lbReporteMotor4.setText("");
        vista.lbReporteMotor5.setText(""); vista.lbReporteMotor6.setText("");
        vista.lbReporteMotor7.setText("");
        vista.lbReporteEjes1.setText(""); vista.lbReporteEjes2.setText("");
        vista.lbReporteEjes3.setText(""); vista.lbReporteEjes4.setText("");
        //    lbReporteEjes5
        vista.lbReporteEjes5.setText(""); vista.lbReporteEjes6.setText(""); 
        vista.lbReporteEjes7.setText("");        
        vista.lbReporteEjesN1.setText(""); vista.lbReporteEjesN2.setText("");
        vista.lbReporteEjesN3.setText(""); vista.lbReporteEjesN4.setText(""); 
        vista.lbReporteEjesN5.setText(""); vista.lbReporteEjesN6.setText(""); 
        vista.lbReporteEjesN7.setText("");
        vista.jLJubilacionesMotor.setText(""); vista.jLJubilacionesEje.setText("");
        vista.jLvacacionesMotor.setText(""); vista.jLvacacionesEJes.setText("");
        vista.lbdifEjes.setText(""); vista.lbdifMotores.setText("");
    }
    // Llenar campos modelos
    public void llenarcamposmodelos(){
        if (jCselectModelo2.getSelectedIndex() > 0){
            vista.lbReporteModelo1.setText(jCselectModelo2.getSelectedItem().toString());
        }
        if (jCselectModelo3.getSelectedIndex() > 0){
            vista.lbReporteModelo2.setText(jCselectModelo3.getSelectedItem().toString());
        }
        if (jCselectModelo4.getSelectedIndex() > 0){
            vista.lbReporteModelo3.setText(jCselectModelo4.getSelectedItem().toString());
        }
        if (jCselectModelo5.getSelectedIndex() > 0){
            vista.lbReporteModelo4.setText(jCselectModelo5.getSelectedItem().toString());
        }
        if (jCselectModelo6.getSelectedIndex() > 0){
            vista.lbReporteModelo5.setText(jCselectModelo6.getSelectedItem().toString());
        }
        if (jCselectModelo7.getSelectedIndex() > 0){
            vista.lbReporteModelo6.setText(jCselectModelo7.getSelectedItem().toString());
        }
        if (jCselectModelo8.getSelectedIndex() > 0){
            vista.lbReporteModelo7.setText(jCselectModelo8.getSelectedItem().toString());
        }        
    }
    // Llenar campos de etiquetas de cantidad
    public void llenarcamposcantidad(){
        if (!vista.lbReporteModelo1.getText().isEmpty()){
            vista.lbReporteCantidad1.setText(jSpincantModelo2.getValue().toString());
        }
        if (!vista.lbReporteModelo2.getText().isEmpty()){
            vista.lbReporteCantidad2.setText(jSpinCantModelo3.getValue().toString());
        }
        if (!vista.lbReporteModelo3.getText().isEmpty()){ 
            vista.lbReporteCantidad3.setText(jSpinCantModelo4.getValue().toString());
        }
        if (!vista.lbReporteModelo4.getText().isEmpty()){
            vista.lbReporteCantidad4.setText(jSpincantModelo5.getValue().toString());
        }
        if (!vista.lbReporteModelo5.getText().isEmpty()){
            vista.lbReporteCantidad5.setText(jSpincantModelo6.getValue().toString());
        }
        if (!vista.lbReporteModelo6.getText().isEmpty()){
            vista.lbReporteCantidad6.setText(jSpincantModelo7.getValue().toString());
        }
        if (!vista.lbReporteModelo7.getText().isEmpty()){ //jSpinCantModelo8
            vista.lbReporteCantidad7.setText(jSpinCantModelo8.getValue().toString());
        }
    }
    // Llenar campos etiqueta de motores
    public void llenarcamposmotores(){
        if (!vista.lbReporteModelo1.getText().isEmpty()){
            vista.lbReporteMotor1.setText(jLSeleccioneMotor.getText());
        }
        if (!vista.lbReporteModelo2.getText().isEmpty()){
            vista.lbReporteMotor2.setText(jLSeleccioneMotor1.getText());        
        }
        if (!vista.lbReporteModelo3.getText().isEmpty()){
            vista.lbReporteMotor3.setText(jLSeleccioneMotor2.getText());        
        }
        if (!vista.lbReporteModelo4.getText().isEmpty()){
            vista.lbReporteMotor4.setText(jLSeleccioneMotor3.getText());        
        }
        if (!vista.lbReporteModelo5.getText().isEmpty()){
            vista.lbReporteMotor5.setText(jLSeleccioneMotor4.getText());        
        }
        if (!vista.lbReporteModelo6.getText().isEmpty()){
            vista.lbReporteMotor6.setText(jLSeleccioneMotor5.getText());        
        }
        if (!vista.lbReporteModelo7.getText().isEmpty()){
            vista.lbReporteMotor7.setText(jLSeleccioneMotor6.getText());        
        }
    }
    // Llenar campos etiqueta de ejes
    public void llenarcamposejes(){
        if (!vista.lbReporteModelo1.getText().isEmpty()){
            if (jCcantEjes2.getSelectedIndex() >= 0){
                vista.lbReporteEjes1.setText(jCcantEjes2.getSelectedItem().toString());
            }
        }
        if (!vista.lbReporteModelo2.getText().isEmpty()){
            if (jCcantEjes3.getSelectedIndex() >= 0){
                vista.lbReporteEjes2.setText(jCcantEjes3.getSelectedItem().toString());
            }
        }
        if (!vista.lbReporteModelo3.getText().isEmpty()){
            if (jCcantEjes4.getSelectedIndex() >= 0){
                vista.lbReporteEjes3.setText(jCcantEjes4.getSelectedItem().toString());
            }
        }
        if (!vista.lbReporteModelo4.getText().isEmpty()){
            if (jCcantEjes5.getSelectedIndex() >= 0){
                vista.lbReporteEjes4.setText(jCcantEjes5.getSelectedItem().toString());
            }
        }
        if (!vista.lbReporteModelo5.getText().isEmpty()){
            if (jCcantEjes6.getSelectedIndex() >= 0){
                vista.lbReporteEjes5.setText(jCcantEjes6.getSelectedItem().toString());
            }
        }
        if (!vista.lbReporteModelo6.getText().isEmpty()){
            if (jCcantEjes7.getSelectedIndex() >= 0){
                vista.lbReporteEjes6.setText(jCcantEjes7.getSelectedItem().toString());
            }
        }
        if (!vista.lbReporteModelo7.getText().isEmpty()){
            if (jCcantEjes8.getSelectedIndex() >= 0){
                vista.lbReporteEjes7.setText(jCcantEjes8.getSelectedItem().toString());
            }
        }
    }
    // Llenar etiqueta de eje neumatico
    public void llenarcamposEnemumatico(){
        String EN1=null, EN2=null;
        if (!vista.lbReporteModelo1.getText().isEmpty()){
            if (jCselectedEjes2.isSelected()) EN1 = "Si"; else EN1 = "No";
            vista.lbReporteEjesN1.setText(EN1);
        }
        if (!vista.lbReporteModelo2.getText().isEmpty()){
            if (jCselectedEjes3.isSelected()) EN2 = "Si"; else EN2 = "No";
            vista.lbReporteEjesN2.setText(EN2);
        }
        if (!vista.lbReporteModelo3.getText().isEmpty()){
            if (jCselectEjes4.isSelected()) EN2 = "Si"; else EN2 = "No";
            vista.lbReporteEjesN3.setText(EN2);
        }
        if (!vista.lbReporteModelo4.getText().isEmpty()){
            if (jCselectEjes5.isSelected()) EN2 = "Si"; else EN2 = "No";
            vista.lbReporteEjesN4.setText(EN2);
        }
        if (!vista.lbReporteModelo5.getText().isEmpty()){
            if (jCselectEjes6.isSelected()) EN2 = "Si"; else EN2 = "No";
            vista.lbReporteEjesN5.setText(EN2);
        }        
        if (!vista.lbReporteModelo6.getText().isEmpty()){
            if (jCselectEjes7.isSelected()) EN2 = "Si"; else EN2 = "No";
            vista.lbReporteEjesN6.setText(EN2);
        }
        if (!vista.lbReporteModelo7.getText().isEmpty()){
            if (jCselectEjes8.isSelected()) EN2 = "Si"; else EN2 = "No";
            vista.lbReporteEjesN7.setText(EN2);
        }
    }
    // Contador del total de unidades.
    public void totaldeunidades(){
        if ((Integer)jSpincantModelo2.getValue() > 0){            
            js2 = (Integer)jSpincantModelo2.getValue();
        }
        if ((Integer)jSpinCantModelo3.getValue() > 0){
            js3 = (Integer)jSpinCantModelo3.getValue();
        }
        if ((Integer)jSpinCantModelo4.getValue() > 0){
            js4 = (Integer)jSpinCantModelo4.getValue();
        }
        if ((Integer)jSpincantModelo5.getValue() > 0){
            js5 = (Integer)jSpincantModelo5.getValue();
        }
        if ((Integer)jSpincantModelo6.getValue() > 0){
            js6 = (Integer)jSpincantModelo6.getValue();
        }
        if ((Integer)jSpincantModelo7.getValue() > 0){
            js7 = (Integer)jSpincantModelo7.getValue();
        }
        if ((Integer)jSpinCantModelo8.getValue() > 0){
            js8 = (Integer)jSpinCantModelo8.getValue();
        }
        int allunid = js2+js3+js4+js5+js6+js7+js8;
        jLunidad.setText(String.valueOf(allunid).toString());
        if (allunid > 100){
            JOptionPane.showMessageDialog(null, "Cantidad de Unidades Excedida....");
            jBreporte.setVisible(false);
        }else{
            jBreporte.setVisible(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KenworthPronostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KenworthPronostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KenworthPronostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KenworthPronostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KenworthPronostico().setVisible(true);
                    modelos = db.readmodelos();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(KenworthPronostico.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(KenworthPronostico.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLimpiarDat;
    private javax.swing.JButton jBagregarCol;
    private javax.swing.JButton jBreporte;
    private javax.swing.JButton jBvistaPre;
    private javax.swing.JComboBox<String> jCcantEjes2;
    private javax.swing.JComboBox<String> jCcantEjes3;
    private javax.swing.JComboBox<String> jCcantEjes4;
    private javax.swing.JComboBox<String> jCcantEjes5;
    private javax.swing.JComboBox<String> jCcantEjes6;
    private javax.swing.JComboBox<String> jCcantEjes7;
    private javax.swing.JComboBox<String> jCcantEjes8;
    private javax.swing.JCheckBox jCselectEjes4;
    private javax.swing.JCheckBox jCselectEjes5;
    private javax.swing.JCheckBox jCselectEjes6;
    private javax.swing.JCheckBox jCselectEjes7;
    private javax.swing.JCheckBox jCselectEjes8;
    private javax.swing.JComboBox<String> jCselectModelo2;
    private javax.swing.JComboBox<String> jCselectModelo3;
    private javax.swing.JComboBox<String> jCselectModelo4;
    private javax.swing.JComboBox<String> jCselectModelo5;
    private javax.swing.JComboBox<String> jCselectModelo6;
    public javax.swing.JComboBox<String> jCselectModelo7;
    public javax.swing.JComboBox<String> jCselectModelo8;
    private javax.swing.JCheckBox jCselectedEjes2;
    private javax.swing.JCheckBox jCselectedEjes3;
    private javax.swing.JLabel jLNombreApp;
    private javax.swing.JLabel jLSeleccioneMotor;
    private javax.swing.JLabel jLSeleccioneMotor1;
    private javax.swing.JLabel jLSeleccioneMotor2;
    private javax.swing.JLabel jLSeleccioneMotor3;
    private javax.swing.JLabel jLSeleccioneMotor4;
    private javax.swing.JLabel jLSeleccioneMotor5;
    private javax.swing.JLabel jLSeleccioneMotor6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLcant;
    private javax.swing.JLabel jLejeNeum;
    private javax.swing.JLabel jLejes;
    private javax.swing.JLabel jLimagen;
    private javax.swing.JLabel jLimagenApp;
    private javax.swing.JLabel jLmodelo;
    private javax.swing.JLabel jLmotores;
    private javax.swing.JLabel jLtotalUnid;
    public javax.swing.JLabel jLunidad;
    private javax.swing.JMenuBar jMenuProno;
    private javax.swing.JMenu jPanelAgregar;
    private javax.swing.JPanel jPanelImagen;
    private javax.swing.JPanel jPanelPronos;
    private javax.swing.JPanel jPejecucionPron;
    private javax.swing.JPanel jPlinea2;
    private javax.swing.JPanel jPlinea3;
    private javax.swing.JPanel jPlinea4;
    private javax.swing.JPanel jPlinea5;
    private javax.swing.JPanel jPlinea6;
    private javax.swing.JPanel jPlinea7;
    private javax.swing.JPanel jPlinea8;
    public javax.swing.JSpinner jSpinCantModelo3;
    private javax.swing.JSpinner jSpinCantModelo4;
    public javax.swing.JSpinner jSpinCantModelo8;
    public javax.swing.JSpinner jSpincantModelo2;
    public javax.swing.JSpinner jSpincantModelo5;
    public javax.swing.JSpinner jSpincantModelo6;
    public javax.swing.JSpinner jSpincantModelo7;
    private com.toedter.calendar.JDateChooser jdPronostico;
    private javax.swing.JMenuItem mItemAgregarModel;
    private javax.swing.JMenuItem mItemConfig;
    private javax.swing.JMenuItem mItemNuevoP;
    private javax.swing.JMenuItem mItemSalir;
    private javax.swing.JMenu menuConfiguracion;
    private javax.swing.JMenu menuProno;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
